"""Refactor Schema with Accounts

Revision ID: 68be55c7726e
Revises: 
Create Date: 2025-11-30 17:27:20.484139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68be55c7726e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('cvv2', sa.String(length=4), nullable=False),
    sa.Column('expire_month', sa.SmallInteger(), nullable=False),
    sa.Column('expire_year', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('hashed_pin', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_card_number'), 'cards', ['card_number'], unique=True)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_card_id', sa.Integer(), nullable=True),
    sa.Column('dest_card_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('fee_amount', sa.BigInteger(), nullable=True),
    sa.Column('total_amount', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('ref_number', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dest_card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['source_card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('idx_dest_created', 'transactions', ['dest_card_id', 'created_at'], unique=False)
    op.create_index('idx_source_created', 'transactions', ['source_card_id', 'created_at'], unique=False)
    op.create_index('idx_status_created', 'transactions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_ref_number'), 'transactions', ['ref_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_ref_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index('idx_status_created', table_name='transactions')
    op.drop_index('idx_source_created', table_name='transactions')
    op.drop_index('idx_dest_created', table_name='transactions')
    op.drop_index('idx_created_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_number'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
